### ISSUE TITLE
SENSU_EVENT_LABEL

### ISSUE THREAD

**Issue by leventogut** [sensu/sensu-pagerduty-handler#23]
Hi,

SENSU_EVENT_LABEL is empty therefore the integration is not working, is sensu suppose to fill in or do we need to create it and if so what would be the value?

**Comment by eric-kinsa** [comment]
I don't see this environment variable (SENSU_EVENT_LABEL) in any of Sensu's docs. It doesn't exist, so I'm not sure how the current release is working for anyone. I downgraded to v1.1.0 of this handler to get it working.

**Comment by ericxnelson** [comment]
confirmed, 1.1.0 ftw (for now)

**Comment by tarcinil** [comment]
I believe that this is only an example and that you should be using your own label in place rather than using `SENSU_EVENT_LABEL`.  I think this could be called out as an example much clearer.

Based on https://github.com/sensu/sensu-pagerduty-handler/blob/master/main.go#L139

This will use the value of the label that it will attempt to use as a dedup key to the pagerduty request.

**Comment by mikeeaton83** [comment]
+1 on this - I've spent hours trying to figure out what was wrong as I thought 'SENSU_EVENT_LABEL' was a special variable or already set somewhere..
